services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    restart: unless-stopped
    ports:
      - "8092:8090"
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8092/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pocketbase_data:
  pocketbase_public:
